### ISSUE TITLE
First issue submit for youtube video player

### ISSUE THREAD

**Issue by lmaldonadoch** [lmaldonadoch/youtube-video-player-page#2]
Please comment on this

**Comment by Stricks1** [comment]
comment test

**Comment by JasemDuncan** [comment]
Nice code, maybe you should work in the size and position of the navigation bar. Greetings.

**Comment by chirchir12** [comment]
you can add a little left padding on the search input. and also try to work on the video responsive

**Comment by Stricks1** [comment]
I liked the code and the idea of using a lib to help on css, it's getting cool already I'll just say to take a look on the hamburger menu to not get stuck on left.
